language: python

python:
  - 2.7

before_install:
 - sudo apt-get update -qq

install:
 - sudo apt-get install -y python-software-properties
 - sudo apt-add-repository -y ppa:git-core/ppa
 - sudo apt-add-repository -y ppa:ubuntugis/ppa
 - sudo apt-get update -qq

 # GDAL-fix -- packaging is miserable, no way to obtain libgdal-dev for libgdal1 when libgdal1h available
 - sudo apt-get download -y libgdal-dev
 - sudo dpkg-deb -x libgdal-dev*.deb /
 - sudo ln -sf /usr/lib/libgdal.so.1 /usr/lib/libgdal.so
 - sudo ldconfig
 # GDAL for python... not better
 - pip install --no-install GDAL==1.9.1
 - pushd /home/travis/virtualenv/python2.7/build/GDAL
 - python setup.py build_ext --include-dirs=/usr/include/gdal
 - pip install --no-download GDAL
 - popd

   # Spatialiate
 - sudo apt-get install -y libproj-dev libgeos-dev libspatialite-dev
 - pip install git+git://github.com/tinio/pysqlite.git@extension-enabled#egg=pysqlite

   # This is a dependency of our Django quicktest script
 - pip install argparse --use-mirrors

 - pip install -r requirements.txt

 - pip install coverage

 - pip install flake8 --use-mirrors

 - python setup.py develop

before_script:
 - flake8 --ignore=E501 mapentity

script:
 - python demo/manage.py test
 - coverage run --include="demo/*" demo/manage.py tests

after_success:
 - pip install coveralls
 - coveralls
